# Generated by Django 5.1.7 on 2025-05-29 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association_greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='제목을 입력해주세요', null=True)),
                ('content', models.TextField(default='내용을 입력해주세요', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='대외활동', max_length=200)),
                ('sub_title', models.TextField(null=True)),
                ('content', models.TextField(default='content', null=True)),
                ('img', models.ImageField(null=True, upload_to='media/Contests')),
            ],
        ),
        migrations.CreateModel(
            name='History_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History_set_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_type', models.TextField(default='history', null=True)),
                ('title', models.TextField(default='2025', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='자격증', max_length=255, null=True)),
                ('content', models.TextField(default=None, null=True)),
                ('headerImage', models.ImageField(default='media/default.png', null=True, upload_to='media/license')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='국내전시', max_length=252)),
                ('sub_title', models.TextField(default='글로벌 플로리스트 주요사업', null=True)),
                ('content', models.TextField(null=True)),
                ('headerImage', models.ImageField(null=True, upload_to='media/Local')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='공지 제목을 입력하세요', null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(default=None, null=True, upload_to='media/new_img')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('issue', '최근이슈'), ('report', '보도자료')], default='issue', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ORGANIZATION_DIRECTOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/Organizational')),
                ('name', models.CharField(max_length=10, null=True)),
                ('position', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ORGANIZATION_PRESIDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/Organizational')),
                ('name', models.CharField(max_length=10, null=True)),
                ('position', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ORGANIZATION_VICE_PRESIDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/Organizational')),
                ('name', models.CharField(max_length=10, null=True)),
                ('position', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Organizational_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('sorting', models.IntegerField(default=3)),
                ('title_img', models.ImageField(upload_to='media/Organizational')),
            ],
        ),
        migrations.CreateModel(
            name='Overseas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='국외전시', max_length=252)),
                ('sub_title', models.TextField(default='글로벌 플로리스트 주요사업', null=True)),
                ('content', models.TextField(null=True)),
                ('headerImage', models.ImageField(null=True, upload_to='media/Overseas')),
            ],
        ),
        migrations.CreateModel(
            name='Contests_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='대외활동', max_length=200)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('place', models.TextField(null=True)),
                ('contests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_title', to='api.contests')),
            ],
        ),
        migrations.CreateModel(
            name='Contests_Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('contests_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests_block', to='api.contests_content')),
            ],
        ),
        migrations.CreateModel(
            name='Greeting_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.TextField(default='국제꽃예술인협회', null=True)),
                ('position', models.TextField(default='이 사 장', null=True)),
                ('name', models.TextField(default='김 세 은', null=True)),
                ('greeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greeting_user', to='api.association_greeting')),
            ],
        ),
        migrations.CreateModel(
            name='History_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='content add', null=True)),
                ('img', models.ImageField(null=True, upload_to='media/history_img')),
                ('history_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.history_content')),
            ],
        ),
        migrations.AddField(
            model_name='history_content',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.history_set_up'),
        ),
        migrations.CreateModel(
            name='License_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/default.png', null=True, upload_to='media/license')),
                ('information', models.TextField(default=None, null=True)),
                ('hyperlink', models.TextField(default=None, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_certification', to='api.license')),
            ],
        ),
        migrations.CreateModel(
            name='Local_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='flower', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default=None, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/Local_sub_content')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_mainImg', to='api.local')),
            ],
        ),
        migrations.CreateModel(
            name='News_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title input', max_length=50)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('issue', '최근이슈'), ('report', '보도자료')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.news')),
            ],
        ),
        migrations.CreateModel(
            name='Notice_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_content', to='api.notice')),
            ],
        ),
        migrations.CreateModel(
            name='ORGANIZATION_DIRECTOR_PROFILE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None)),
                ('ORGANIZATION_DIRECTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization_director')),
            ],
        ),
        migrations.CreateModel(
            name='ORGANIZATION_PRESIDENT_PROFILE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None)),
                ('ORGANIZATION_PRESIDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization_president')),
            ],
        ),
        migrations.CreateModel(
            name='ORGANIZATION_VICE_PRESIDENT_PROFILE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None)),
                ('ORGANIZATION_VICE_PRESIDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization_vice_president')),
            ],
        ),
        migrations.CreateModel(
            name='Organizational_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizational_chart')),
            ],
        ),
        migrations.CreateModel(
            name='Overseas_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='flower', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default=None, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/Overseas_sub_content')),
                ('overseas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overseas_mainImg', to='api.overseas')),
            ],
        ),
    ]
