# Generated by Django 5.1.7 on 2025-04-02 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association_greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='제목을 입력해주세요', null=True)),
                ('content', models.TextField(default='내용을 입력해주세요', null=True)),
                ('name', models.CharField(default='이름을 입력해주세요', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Association_history_month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.TextField(default='2026.04')),
                ('content', models.TextField(default='내용')),
                ('img', models.ImageField(null=True, upload_to='history_img')),
            ],
        ),
        migrations.CreateModel(
            name='Association_history_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(default='2026')),
            ],
        ),
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='대외활동', max_length=200)),
                ('sub_title', models.TextField(null=True)),
                ('content', models.TextField(default='content', null=True)),
                ('img', models.ImageField(null=True, upload_to='Contests')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='국외전시', max_length=252)),
                ('sub_title', models.TextField(default='글로벌 플로리스트 주요사업', null=True)),
                ('content', models.TextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='Overseas')),
            ],
        ),
        migrations.CreateModel(
            name='License_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='자격증', max_length=200)),
                ('content', models.TextField(default='content', null=True)),
                ('img', models.ImageField(null=True, upload_to='License')),
                ('license_script', models.TextField(default='content', null=True)),
                ('link', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='국내전시', max_length=252)),
                ('sub_title', models.TextField(default='글로벌 플로리스트 주요사업', null=True)),
                ('content', models.TextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='Local')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='공지 제목을 입력하세요', null=True)),
                ('type', models.IntegerField(default=1, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('issue', '최근 이슈'), ('press', '보도자료')], default='최근이슈', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Overseas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='국외전시', max_length=252)),
                ('sub_title', models.TextField(default='글로벌 플로리스트 주요사업', null=True)),
                ('content', models.TextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='Overseas')),
            ],
        ),
        migrations.CreateModel(
            name='Contests_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='대외활동', max_length=200)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('place', models.TextField(null=True)),
                ('contests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_title', to='api.contests')),
            ],
        ),
        migrations.CreateModel(
            name='Contests_Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('contests_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests_block', to='api.contests_content')),
            ],
        ),
        migrations.CreateModel(
            name='Local_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='flower', max_length=100)),
                ('content', models.TextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='Local_sub_content')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.local')),
            ],
        ),
        migrations.CreateModel(
            name='News_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.news')),
            ],
        ),
        migrations.CreateModel(
            name='Notice_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_content', to='api.notice')),
            ],
        ),
        migrations.CreateModel(
            name='Overseas_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='flower', max_length=100)),
                ('content', models.TextField(null=True)),
                ('img', models.ImageField(null=True, upload_to='Overseas_sub_content')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('overseas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.overseas')),
            ],
        ),
    ]
