# Generated by Django 5.1.7 on 2025-05-29 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_license_content_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contests',
            old_name='img',
            new_name='headerImage',
        ),
        migrations.RenameField(
            model_name='contests_content',
            old_name='place',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='contests_content',
            old_name='upload_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='contests',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='contests_content',
            name='location',
            field=models.TextField(default='내용이 없습니다.', null=True),
        ),
        migrations.AddField(
            model_name='contests_content',
            name='mainImage',
            field=models.ImageField(default='/media/default.png', null=True, upload_to='media/contents'),
        ),
        migrations.CreateModel(
            name='Content_florist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름', max_length=100, null=True)),
                ('target_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_florist', to='api.contests_content')),
            ],
        ),
    ]
