# Generated by Django 5.1.7 on 2025-04-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_history_content_history_event_history_set_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_event',
            name='img',
            field=models.ImageField(null=True, upload_to='media/history_img'),
        ),
    ]
