# Generated by Django 5.1.7 on 2025-05-30 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_img_contests_headerimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default=None, null=True)),
                ('image', models.ImageField(default='/media/defalut.png', null=True, upload_to='media/content')),
                ('target_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_gallery', to='api.contests_content')),
            ],
        ),
        migrations.DeleteModel(
            name='Contests_Block',
        ),
    ]
