# Generated by Django 5.1.7 on 2025-04-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_history_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='img',
            field=models.ImageField(null=True, upload_to='media/Contests'),
        ),
        migrations.AlterField(
            model_name='license',
            name='img',
            field=models.ImageField(null=True, upload_to='media/Overseas'),
        ),
        migrations.AlterField(
            model_name='license_content',
            name='img',
            field=models.ImageField(null=True, upload_to='media/License'),
        ),
        migrations.AlterField(
            model_name='local',
            name='img',
            field=models.ImageField(null=True, upload_to='media/Local'),
        ),
        migrations.AlterField(
            model_name='local_content',
            name='img',
            field=models.ImageField(null=True, upload_to='media/Local_sub_content'),
        ),
        migrations.AlterField(
            model_name='overseas',
            name='img',
            field=models.ImageField(null=True, upload_to='media/Overseas'),
        ),
        migrations.AlterField(
            model_name='overseas_content',
            name='img',
            field=models.ImageField(null=True, upload_to='media/Overseas_sub_content'),
        ),
    ]
