# Generated by Django 5.1.7 on 2025-05-30 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contents_gallery_delete_contests_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents_gallery',
            name='target_content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_gallery', to='api.contests_content'),
        ),
    ]
