# Generated by Django 5.1.7 on 2025-04-04 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contests_img_alter_license_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizational_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('title_img', models.ImageField(upload_to='media/Organizational')),
            ],
        ),
        migrations.CreateModel(
            name='Organizational_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizational_chart')),
            ],
        ),
    ]
