# Generated by Django 5.1.7 on 2025-04-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_organizational_chart_organizational_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_set_up',
            name='title',
            field=models.TextField(default='2025', unique=True),
        ),
    ]
