# Generated by Django 5.1.7 on 2025-05-30 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contents_gallery_target_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents_gallery',
            name='target_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_gallery', to='api.contests'),
        ),
    ]
