# Generated by Django 5.1.7 on 2025-04-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_history_set_up_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.TextField(default='국제꽃예술인협회', null=True)),
                ('position', models.TextField(default='이 사 장', null=True)),
                ('name', models.TextField(default='김 세 은', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='association_greeting',
            name='name',
        ),
    ]
