# Generated by Django 5.1.7 on 2025-05-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_contents_gallery_target_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='upload_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='notice_content',
            old_name='order',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='notice_content',
            name='block_type',
        ),
        migrations.AddField(
            model_name='notice_content',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notice_content',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
