# Generated by Django 5.1.7 on 2025-05-30 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_upload_date_notice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_content',
            name='notice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notice_content', to='api.notice'),
        ),
    ]
