# Generated by Django 5.1.7 on 2025-04-14 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_greeting_user_remove_association_greeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting_user',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.association_greeting'),
        ),
    ]
