# Generated by Django 5.1.7 on 2025-04-14 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_greeting_user_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting_user',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greeting_user', to='api.association_greeting'),
        ),
    ]
