# Generated by Django 5.1.7 on 2025-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_notice_content_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_content',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
