# Generated by Django 5.1.7 on 2025-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notice_content_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents_gallery',
            name='image',
            field=models.ImageField(blank=True, default='/media/defalut.png', null=True, upload_to='media/content'),
        ),
        migrations.AlterField(
            model_name='contests',
            name='headerImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/Contests'),
        ),
        migrations.AlterField(
            model_name='history_event',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/history_img'),
        ),
        migrations.AlterField(
            model_name='license',
            name='headerImage',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='media/license'),
        ),
        migrations.AlterField(
            model_name='local',
            name='headerImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/Local'),
        ),
        migrations.AlterField(
            model_name='local_content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Local_sub_content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/new_img'),
        ),
        migrations.AlterField(
            model_name='organization_director',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Organizational'),
        ),
        migrations.AlterField(
            model_name='organization_president',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Organizational'),
        ),
        migrations.AlterField(
            model_name='organization_vice_president',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Organizational'),
        ),
        migrations.AlterField(
            model_name='organizational_chart',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/Organizational'),
        ),
        migrations.AlterField(
            model_name='overseas_content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Overseas_sub_content'),
        ),
    ]
