# Generated by Django 5.1.7 on 2025-04-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_greeting_user_greeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizational_chart',
            name='sorting',
            field=models.IntegerField(default=3),
        ),
    ]
