# Generated by Django 5.1.7 on 2025-06-18 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_contents_gallery_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='sub_title',
            new_name='subTitle',
        ),
    ]
