# Generated by Django 5.1.7 on 2026-02-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_sub_title_local_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('issues', '최근이슈'), ('report', '보도자료')], default='issue', max_length=10),
        ),
        migrations.AlterField(
            model_name='news_content',
            name='type',
            field=models.CharField(choices=[('issues', '최근이슈'), ('report', '보도자료')], max_length=50),
        ),
    ]
