# Generated by Django 5.1.7 on 2026-08-25 00:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_news_type_alter_news_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contents_gallery',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='contests_content',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='local_content',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='news_content',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='notice_content',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='overseas_content',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='contents_gallery',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contests_content',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='local_content',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice_content',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='overseas_content',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Notice_attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/notice_files')),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.notice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
